---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=1in

title: "`r format(Sys.time(), '%B %Y')`"
author: Mochen Yang

jobtitle: "Associate Professor, Carlson School of Management, University of Minnesota"
address: "CSOM 3-151, 321 19th Ave S, Minneapolis, MN"
#fontawesome: yes
email: yang3653@umn.edu
#github: mochenyang
phone: "612-625-7324"
web: mochenyang.github.io

#fontfamily: mathpazo
#fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# ACADEMIC APPOINTMENTS

**Carlson School of Management, University of Minnesota**

-   Associate Professor, Department of Information and Decision Sciences \hfill 2023 - present
-   Assistant Professor, Department of Information and Decision Sciences \hfill 2019 - 2023

**Kelley School of Business, Indiana University**

-   Assistant Professor, Department of Operations & Decision Technologies \hfill 2018 - 2019

\hrulefill

# EDUCATION

**Carlson School of Management, University of Minnesota** \hfill 2013 - 2018

-   PhD in Business Administration, Department of Information & Decision Sciences
-   *Thesis*: Towards a Comprehensive Understanding of User-Generated Content and Engagement Behavior on Facebook Business Pages
-   *Committee*: Yuqing Ren (Advisor), Gediminas Adomavicius (Advisor), Gordon Burtch, Jisu Huh

**School of Economics and Management, Tsinghua University** \hfill 2009 - 2013

-   Bachelor of Information Management and Information System

**Rotman School of Management, University of Toronto** \hfill 9/2011 - 12/2011

-   Exchange Student

\hrulefill

# JOURNAL PUBLICATIONS

1.  Bi X, Gupta A, Yang M. Understanding Partnership Formation and Repeated Contributions in Federated Learning: An Analytical Investigation. ***Management Science**, forthcoming*.

2.  Cheng X, Bala H, Yang M. User Engagement on Social Media Business Pages: The Interplay between User Comments and Firm Responses. ***MIS Quarterly***, *forthcoming*.

3.  Liu C, Yang M, Wen M. Judge Me on My Losers: Does Adaptive Robo-Advisors Outperform Human Investors during the COVID-19 Financial Market Crash? ***Production and Operations Management***, *forthcoming*.

4.  Bi X, Yang M, Adomavicius G. Consumer Acquisitions for Recommender Systems: A Theoretical Framework and Empirical Evaluations. ***Information Systems Research***, *forthcoming*.

5.  Travadi Y, Peng L, Bi X, Sun J, Yang, M. Welfare and Fairness Dynamics in Federated Learning: A Client Selection Perspective. ***Statistics and Its Interface***, *forthcoming*.

6.  Kim A, Yang M, Zhang J (2023). When Algorithms Err: Differential Impact of Early vs. Late Errors on Users' Reliance on Algorithms. ***ACM Transactions on Computer-Human Interaction (TOCHI)***, 30(1), 1-36.

7.  Yang M, McFowland E, Burtch G, Adomavicius G (2022). Achieving Reliable Causal Inference with Data-Mined Variables: A Random Forest Approach to the Measurement Error Problem. ***INFORMS Journal on Data Science (IJDS)*** 1(2), 115-195.

8.  Adomavicius G, Yang M. (2022). Integrating Behavioral, Economic, and Technical Insights to Understand and Address Algorithmic Bias: A Human-Centric Perspective. ***ACM Transactions on Management Information Systems (TMIS)***, 13(3), 1-27.

    -   Selected Media Coverage: [The Carlson School Magazine (Spring 2022)](https://carlsonschool.umn.edu/magazine)

9.  Adomavicius G, Gupta A, & Yang M (2022). Bidder Support in Multi-Item Multi-Unit Continuous Combinatorial Auctions: A Unifying Theoretical Framework. ***Information Systems Research***, 33(4),1174-1195.

10. Yang M, Ren Y, & Adomavicius G. (2020) Engagement by Design: An Empirical Study of the "Reactions" Feature on Facebook Business Pages. ***ACM Transactions on Computer-Human Interaction (TOCHI)***, 27(6), 1-35.

    -   Selected Media Coverage: [Discover at Carlson](https://carlsonschool.umn.edu/news/wisdom-crowds-its-complicated)

11. Adomavicius G, Gupta A, & Yang M. (2019). Designing Real-Time Feedback for Bidders in Homogeneous-Item Continuous Combinatorial Auctions. ***MIS Quarterly***, 43(3), 721-743.

12. Yang M, Adomavicius G, & Gupta A. (2019). Efficient Computational Strategies for Dynamic Inventory Liquidation. ***Information Systems Research***, 30(2), 595--615.

13. Yang M, Ren Y, & Adomavicius G. (2019) Understanding User-Generated Content and Customer Engagement on Facebook Business Pages. ***Information Systems Research***, 30(3), 839--855.

    -   Selected Media Coverage: [INFORMS Press Release](https://www.informs.org/About-INFORMS/News-Room/Press-Releases/New-Research-Shows-Negative-Posts-on-Facebook-Business-Pages-Outweigh-Positive-Posts-2-to-1-The-Impact-it-s-Having-on-Brands-and-Profitability), [INFORMS "Resoundingly Human" Podcast](https://pubsonline.informs.org/do/10.1287/orms.2019.06.27p/full/), [EurekAlert](https://eurekalert.org/pub_releases/2019-09/ifor-npo091319.php), [Tech Xplore](https://techxplore.com/news/2019-09-negative-facebook-business-pages-outweigh.html), [eurasia review](https://www.eurasiareview.com/14092019-negative-posts-on-facebook-business-pages-outweigh-positive-posts-2-to-1/), [EDWEEK Market Brief](https://marketbrief.edweek.org/marketplace-k-12/negative-posts-facebook-business-pages-outnumber-positive-2-1-research-says/)

14. Yang M, Adomavicius G, Burtch G, & Ren Y. (2018). Mind the Gap: Accounting for Measurement Error and Misclassification in Variables Generated via Data Mining. ***Information Systems Research***, 29(1), 4-24.

    -   Appears in [INFORMS Editor's Cut on Artificial Intelligence](https://pubsonline.informs.org/editorscut/AI-ML/data-analytics)

\hrulefill

# WORKING PAPERS

1.  Tan X, Yang M, Wang G. Promoting Algorithm Adoption in the Presence of Human Experts: A Field Study.

2.  Burtch G, Yang M, McFowland E, Adomavicius G. EnsembleIV: Creating Instrumental Variables from Ensemble Learners for Robust Statistical Inference.

3.  Yang M, Bi X. Cost-Aware Calibration of Classifiers.

4.  Zhang J, Yang M, Bi X, Wei Q. Algorithmic Governance of Two-Sided Platforms: the Case of Short Video Recommendation.

\hrulefill

# CONFERENCE PAPERS AND PRESENTATIONS

(presentations marked by [$\checkmark$])

1.  Zhang J, Yang M, Bi X, Wei Q. Algorithmic Governance of Two-Sided Platforms: the Case of Short Video Recommendation.

    -   INFORMS Annual Meeting, Phoenix, Arizona, 2023.

2.  Zandvakili R, Chan J, Hedgcock W, Yang M. Predicting Customers' Recall Using Psychophysiological Measures.

    -   INFORMS Annual Meeting, Indianapolis, Indiana, 2022.
    -   Conference on Digital Experimentation (***CODE***), Boston, Massachusetts, 2022.

3.  Burtch G, Yang M, McFowland E, Adomavicius G. EnsembleIV: Creating Instrumental Variables from Ensemble Learners for Robust Statistical Inference.

    -   [$\checkmark$]INFORMS Workshop on Data Science, Indianapolis, Indiana, 2022. (**Best Paper Award**)

4.  Yoon S, Subramani G, Subramani M, Yang M. The Effect of Peer-to-Peer Tangible Donation on Donors and Receivers Participation in Online Charity Platform.

    -   International Conference on Information Systems (***ICIS***), Copenhagen, Denmark, 2022.
    -   Statistical Challenges in Electronic Commerce Research (***SCECR***), Madrid, Spain, 2022.

5.  Liu C, Yang M, Wen M. Judge Me on My Losers: Does Adaptive Robo-Advisors Outperform Human Investors during the COVID-19 Financial Market Crash?

    -   Conference on Information Systems and Technology (***CIST***), Newport Beach, California, 2021.

6.  Yang M, Bi X. The Goldilocks Principle of Cooperation: Understanding Federated Learning in Healthcare via Iterated Prisoner's Dilemma.

    -   [$\checkmark$]China Summer Workshop on Information Management (***CSWIM***), Virtual, 2021.
    -   [$\checkmark$]Conference on Information Systems and Technology (***CIST***), Newport Beach, California, 2021.

7.  Kim A, Yang M, Zhang J. When Algorithms Err: Differential Impact of Early vs. Late Errors on Users' Reliance on Algorithms.

    -   [$\checkmark$]Conference on Artificial Intelligence, Machine Learning, and Business Analytics, Virtual, 2020.
    -   Conference on Information Systems and Technology (***CIST***), Virtual, 2020.

8.  Bi X, Yang M, Adomavicius G. Consumer Acquisitions for Recommender Systems: A Theoretical Framework and Empirical Validations.

    -   [$\checkmark$]Workshop on Information Technologies and Systems (***WITS***), Virtual, 2020.
    -   [$\checkmark$]INFORMS Annual Meeting, Virtual, 2020.
    -   Winter Conference on Business Analytics (***WCBA***), Snowbird, Utah, 2020.

9.  Tan X, Yang M, Wang G. Managing Adoption of Artificial Intelligence in the Presence of Human Intelligence: A Field Study.

    -   Conference on Artificial Intelligence, Machine Learning, and Business Analytics, Philadelphia, Pennsylvania, 2019.

10. Yang M, McFowland E, Burtch G, Adomavicius G. Seeing the Forest for the Trees: Generating Instrumental Variables via Random Forest to Address Endogeneity due to Prediction Error in Data-Mined Variables.

    -   Winter Conference on Business Analytics (***WCBA***), Snowbird, Utah, 2019.
    -   [$\checkmark$]Conference on Digital Experimentation (***CODE***), Boston, Massachusetts, 2018.
    -   [$\checkmark$]INFORMS Workshop on Data Science, Phoenix, Arizona, 2018. (**Best Paper Nomination**)

11. Yang M, Ren Y, & Adomavicius G. Engagement by Design: An Empirical Study of the "Reactions" Feature on Facebook Business Pages.

    -   [$\checkmark$]Workshop on Information Technologies and Systems (***WITS***), Seoul, Korea, 2017.
    -   [$\checkmark$]Conference on Information Systems and Technology (***CIST***), Houston, Texas, 2017.
    -   [$\checkmark$]Winter Conference on Business Analytics (***WCBA***), Snowbird, Utah, 2017.

12. Adomavicius G, Gupta A, & Yang M. Providing Real-Time Bidder Support in Homogeneous Item Combinatorial Auctions.

    -   [$\checkmark$]Workshop on Information Technologies and Systems (***WITS***), Dublin, Ireland, 2016.

13. Yang M, Adomavicius G, Burtch G, & Ren Y. Mind the Gap: Accounting for Measurement Error and Misclassification in Variables Generated via Machine Learning.

    -   [$\checkmark$]Winter Conference on Business Intelligence (***WCBI***), Snowbird, Utah, 2016.

14. Adomavicius G, Gupta A, & Yang M. Computational Strategies for Inventory Liquidation.

    -   [$\checkmark$]Workshop on Information Technologies and Systems (***WITS***), Dallas, Texas, 2015.

15. Yang M, Ren Y, & Adomavicius G. Understanding Word-of-Mouth and Customer Engagement on Facebook Business Pages.

    -   [$\checkmark$]Conference on Information Systems and Technology (***CIST***), San Francisco, California, 2014.

\hrulefill

# INVITED TALKS AND SEMINARS

1.  Understanding Partnership Formation and Repeated Contributions in Federated Learning: An Analytical Investigation, School of Economics and Management, Tsinghua University, Virtual, 2022.

2.  Robust Statistical Inference with ML-Generated Variables, Wisconsin School of Business, University of Wisconsin-Madison, 2022.

3.  Artificial Intelligence and Analytics Symposium, Lubar School of Business, University of Wisconsin-Milwaukee, 2022.

4.  Understanding Federated Learning in Healthcare via Iterated Prisoner's Dilemma. McCombs School of Business, University of Texas at Austin, 2022.

5.  Understanding Federated Learning in Healthcare via Iterated Prisoner's Dilemma. IDSc Departmental Friday Seminar, 2022.

6.  Understanding Federated Learning in Healthcare via Iterated Prisoner's Dilemma. Carlson School Summer Applied Economics Seminar Series, 2021.

7.  Analyzing User-Generated Content on Firms' Social Media Pages. Twin Cities Knowledge Management Forum, 2019.

8.  Achieving Reliable Causal Inference with Data-Mined Variables: A Random Forest Approach to the Measurement Error Problem. George Washington University School of Business, George Washington University, Washington, D.C., 2019.

9.  Seeing the Forest for the Trees: Generating Instrumental Variables with Random Forest for Bias Correction in Statistical Inferences. School of Economics and Management, Tsinghua University, Beijing, China, 2018.

10. Seeing the Forest for the Trees: Generating Instrumental Variables with Random Forest for Bias Correction in Statistical Inferences. INFORMS Session - Business Applications of Artificial Intelligence, Phoenix, Arizona, 2018.

11. Understanding Word-of-Mouth and Customer Engagement on Facebook Business Pages. University of Georgia, Terry College of Business, Athens, Georgia, 2017 (Job Talk).

12. Mind the Gap: Accounting for Measurement Error and Misclassification in Variables Generated via Data Mining. Carnegie Mellon University, Tepper School of Business, Pittsburgh, Pennsylvania, 2017 (Job Talk).

13. Mind the Gap: Accounting for Measurement Error and Misclassification in Variables Generated via Data Mining. Indiana University, Kelley School of Business, Bloomington, Indiana, 2017 (Job Talk).

14. Mind the Gap: Accounting for Measurement Error and Misclassification in Variables Generated via Data Mining. New York University, Stern School of Business, New York, 2017 (Job Talk).

15. Analyzing User-Generated Content on Firm-Hosted Social Media Pages. Financial and Retail Conference (***FARCON***), MinneAnalytics, 2017.

16. Understanding Word-of-Mouth and Customer Engagement on Facebook Business Pages. Social Media and Business Analytics Collaborative (***SOBACO***) Symposium, Carlson School of Management, 2015.

\hrulefill

# TEACHING

**Teaching at University of Minnesota**

-   MSBA 6130: Introduction to Business Analytics in R
-   MSBA 6440: Causal Inference via Econometrics and Experiments
-   MSBA 6460: Advanced AI for Business Application
-   CHEMBA Residency Program: Business Analytics

**Teaching at Indiana University**

-   K353: Business Analytics and Modeling, Spring 2019
-   K579: Business Analytics Concepts and Management, Spring 2019
-   C552: IT for Managers: The Strategic Use of Information Technology in Business, one session on Business Application of Machine Learning, Guest Lecturer, Fall 2018, Summer 2019

**Teaching Experiences as PhD Student**

-   IDSc 4444: Descriptive and Predictive Analytics, Instructor, Fall 2016, Spring 2017
-   Predictive Analytics, Guest Lecturer, Fall 2015, Fall 2017
-   Exploratory Data Analytics and Visualization, Guest Lecturer, Fall 2015

\hrulefill

# PROFESSIONAL RECOGNITIONS

**Honors and Awards**

-   MSBA Faculty of the Year (Foundational Course), 2023
-   INFORMS ISS Cluster Best Session Chair Award, 2022
-   MSBA Outstanding Teacher Award (Core Course), 2022
-   Best Reviewer Award, INFORMS Workshop on Data Science, 2021
-   Best Reviewer Award, Conference on Information Systems and Technology (CIST), 2021
-   Best Reviewer Award, Information Systems Research (ISR), 2021
-   MSBA Outstanding Teacher Award (Core Course), 2021
-   MSBA Outstanding Teacher Award (Specialty Course), 2020
-   INFORMS Information Systems Society (ISS) Nunamaker-Chen Dissertation Award, 2018
-   International Conference on Information Systems (ICIS) Doctoral Consortium Attendee, 2017
-   PhD Student Teaching Award, Carlson School of Management, 2016-2017
-   Graduate School Dissertation Fellowship, University of Minnesota, 2017-2018
-   Best Reviewer Award, Workshop on Information Technologies and Systems (WITS), 2016
-   Graduated with Honors, Tsinghua University, 2013
-   National Scholarship, Ministry of Education, China, 2010

**Grants**

-   "Understanding and Improving Federated Learning in Healthcare", Cisco Research, 2021-2022 (\$137,000, co-PI with Xuan Bi)
-   Research Data Grant, Kelley School of Business, Fall 2018 (\$1800)
-   Graduate School Dissertation Fellowship travel grant, Fall 2017 (\$1000)
-   Carlson School PhD Travel Fellowship, 2014-2018, 5 times
-   Department Travel Grant, Carlson School of Management, 2014-2018, 6 times
-   SOBACO Micro-Grants, Carlson School of Management, Fall 2014 (\$1000)

\hrulefill

# STUDENT ADVISING

**Doctoral Students**

-   Liben Chen, Second-Year Paper Committee, 2024
-   Jinghui Zhang, visiting PhD scholar from Tsinghua University, 2022-2023
-   Sojung Yoon, First-Year Exam Committee, 2022
-   Sandeep Gangarapu, Oral Prelim Committee Member, 2022
-   Ramin Zandvakili, Second-Year Paper Committee, 2021
-   Xiaoye Cheng, Dissertation Committee Member, 2019

**Master Students**

-   Yuxuan Yang, MS in Business Analytics, Independent Study Advisor, 2022
-   Tiruo Yan, MS in Data Science, Thesis Advisor, 2022

**Undergraduate Students**

-   Andrius Adomavicius, Honors Thesis, Chair, 2023
-   Alex Dimitrov, Honors Thesis, Reader, 2022

\hrulefill

# SERVICE

**Editorial Appointments**

-   Editorial Review Board, Information Systems Research, 2022-2024

**Conference / Workshop Organization**

-   INFORMS Workshop on Data Science, 2023, Program Committee Co-Chair
-   INFORMS Annual Meeting, 2022, Session Chair (IS Cluster)
-   Americas Conference on Information Systems, 2022, Workshop Co-Chair
-   Workshop on Information Technologies and Systems, 2020, Webmaster
-   Production and Operations Management Society Conference, 2020, Session Chair (Social Media and IOT)
-   INFORMS Annual Meeting, 2020, Session Chair (Social Media and Platform)

**Conference Program Committee Member or Associate Editor**

-   INFORMS Data Science Workshop
-   Winter Conference on Business Analytics
-   International Conference on Information Systems
-   Conference on Information Systems and Technology
-   Workshop on Information Technologies and Systems
-   Pacific Asia Conference on Information Systems

**Reviewer**

-   Information Systems Research
-   MIS Quarterly
-   Management Science
-   Organization Science
-   Production and Operations Management Journal
-   INFORMS Journal on Data Science
-   European Journal of Information Systems
-   ACM Transactions on Management Information Systems
-   Journal of Strategic Information Systems
-   Information Systems Journal
-   International Conference on Information Systems
-   Conference on Information Systems and Technology
-   Pacific Asia Conference on Information Systems
-   Hawaii International Conference on System Sciences

**Departmental Services**

-   Ph.D. Recruiting Committee, University of Minnesota, 2021
-   Junior Faculty Brownbag Organization, University of Minnesota, 2021-2022
-   Faculty Recruiting Committee, University of Minnesota, 2020
-   Ph.D. Recruiting Committee, Indiana University, 2019

**Other Services**

-   VP of Communications, INFORMS Information Systems Society, 2019-2023
-   Diffusion Editor, Organization Science, 2021 - 2023

\hrulefill
